from __future__ import annotations


# Mirror will copy LEFT to RIGHT automatically during PGTrainer._apply_action().
# Keep this as LEFT-side only + shared parameters (midline).
base_expression = {
    "BROW_DOWN_LEFT": 0.0,
    "BROW_DOWN_RIGHT": 0.0,
    "BROW_IN_LEFT": 0.0,
    "BROW_IN_RIGHT": 0.0,
    "BROW_INNER_UP": 0.0,
    "BROW_OUTER_UP_LEFT": 0.0,
    "BROW_OUTER_UP_RIGHT": 0.0,
    "BROW_UP_LEFT": 0.0,
    "BROW_UP_RIGHT": 0.0,
    "BLINK_LEFT": 0.0,
    "BLINK_RIGHT": 0.0,
    "EYE_BLINK_LEFT": 0.0,
    "EYE_BLINK_RIGHT": 0.0,
    "EYE_LOOK_DOWN_LEFT": 0.0,
    "EYE_LOOK_DOWN_RIGHT": 0.0,
    "EYE_LOOK_IN_LEFT": 0.0,
    "EYE_LOOK_IN_RIGHT": 0.0,
    "EYE_LOOK_OUT_LEFT": 0.0,
    "EYE_LOOK_OUT_RIGHT": 0.0,
    "EYE_LOOK_UP_LEFT": 0.0,
    "EYE_LOOK_UP_RIGHT": 0.0,
    "EYE_SQUINT_LEFT": 0.0,
    "EYE_SQUINT_RIGHT": 0.0,
    "EYE_WIDE_LEFT": 0.0,
    "EYE_WIDE_RIGHT": 0.0,
    "MOUTH_CLOSE": 0.0,
    "MOUTH_DIMPLE_LEFT": 0.0,
    "MOUTH_DIMPLE_RIGHT": 0.0,
    "MOUTH_FROWN_LEFT": 0.0,
    "MOUTH_FROWN_RIGHT": 0.0,
    "MOUTH_FUNNEL": 0.0,
    "MOUTH_LEFT": 0.0,
    "MOUTH_LOWER_DOWN_LEFT": 0.0,
    "MOUTH_LOWER_DOWN_RIGHT": 0.0,
    "MOUTH_PRESS_LEFT": 0.0,
    "MOUTH_PRESS_RIGHT": 0.0,
    "MOUTH_PUCKER": 0.0,
    "MOUTH_RIGHT": 0.0,
    "MOUTH_ROLL_LOWER": 0.0,
    "MOUTH_ROLL_UPPER": 0.0,
    "MOUTH_SHRUG_LOWER": 0.0,
    "MOUTH_SHRUG_UPPER": 0.0,
    "MOUTH_SMILE_LEFT": 0.0,
    "MOUTH_SMILE_RIGHT": 0.0,
    "MOUTH_STRETCH_LEFT": 0.0,
    "MOUTH_STRETCH_RIGHT": 0.0,
    "MOUTH_UPPER_UP_LEFT": 0.0,
    "MOUTH_UPPER_UP_RIGHT": 0.0,
    "CHEEK_PUFF": 0.0,
    "CHEEK_SQUINT_LEFT": 0.0,
    "CHEEK_SQUINT_RIGHT": 0.0,
    "JAW_FORWARD": 0.0,
    "JAW_LEFT": 0.0,
    "JAW_OPEN": 0.0,
    "JAW_RIGHT": 0.0,
    "LOOK_LEFT": 0.0,
    "LOOK_RIGHT": 0.0,
    "LOOK_UP": 0.0,
    "LOOK_DOWN": 0.0,
    "NOSE_SNEER_LEFT": 0.0,
    "NOSE_SNEER_RIGHT": 0.0,
}
